#ifndef HELP_HPP
#define HELP_HPP

#define HELP "USAGE:\n \t./arcade ./lib./lib_arcade_<LIB>/<LIB>.so\n\nINPUTS:\n\tKEY FOR PREVIOUS GAME / SELECTION - F2\n\n\tKEY FOR NEXT GAME / SELECTION  - F3\n\n\tKEY FOR NEWGAME - F4\n\n\tKEY FOR MENU - F5\n\n\tKEY FOR PREVIOUS GRAPHICAL - F6\n\n\tKEY FOR NEXT GRAPHICAL - F7\n\n\tKEY FOR EXIT - F12\n\nCONFIGURATION FILE:\n\n\t1,NAME,X,Y,COLOR,FONT SIZE\n\n\t2,SYMBOLE OF ASSETS\n"



#endif